# Generated by Django 4.2.16 on 2026-05-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_hour_window',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_sends_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestrecipient',
            name='verified_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='submissioninbox',
            index=models.Index(fields=['recipient', 'status'], name='submission__recipie_2fc063_idx'),
        ),
    ]
