# Generated by Django 4.2.16 on 2026-05-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_is_favorite_file_files_owner_i_56991e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('upload_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('max_files', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_files', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'file_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'share_analytics_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file_request', 'File Request'), ('direct_share', 'Direct Share Link Upload'), ('anonymous', 'Anonymous Upload')], max_length=30)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_name', models.CharField(blank=True, max_length=255)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_action', 'Needs Action'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, max_length=1000)),
                ('rejection_reason', models.TextField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'submission_inbox',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='fileshare',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='last_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['share_token'], name='file_shares_share_t_68bcb5_idx'),
        ),
        migrations.AddField(
            model_name='submissioninbox',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_entry', to='files.file'),
        ),
        migrations.AddField(
            model_name='submissioninbox',
            name='file_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sharing.filerequest'),
        ),
        migrations.AddField(
            model_name='submissioninbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareanalyticsevent',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sharing.fileshare'),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submissioninbox',
            index=models.Index(fields=['owner', 'status'], name='submission__owner_i_13b6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='submissioninbox',
            index=models.Index(fields=['owner', 'source_type'], name='submission__owner_i_b86a43_idx'),
        ),
        migrations.AddIndex(
            model_name='submissioninbox',
            index=models.Index(fields=['file_request', 'status'], name='submission__file_re_a4ca08_idx'),
        ),
        migrations.AddIndex(
            model_name='shareanalyticsevent',
            index=models.Index(fields=['share', 'event_type'], name='share_analy_share_i_9d2f00_idx'),
        ),
        migrations.AddIndex(
            model_name='shareanalyticsevent',
            index=models.Index(fields=['occurred_at'], name='share_analy_occurre_de89ab_idx'),
        ),
    ]
