# Generated by Django 4.2.16 on 2026-05-12 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_filerequest_shareanalyticsevent_submissioninbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='allowed_extensions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RequestRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('upload_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('upload_count', models.PositiveIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sharing.filerequest')),
            ],
            options={
                'db_table': 'request_recipients',
                'ordering': ['created_at'],
                'unique_together': {('file_request', 'email')},
            },
        ),
        migrations.AddField(
            model_name='submissioninbox',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sharing.requestrecipient'),
        ),
    ]
