# Generated by Django 4.2.16 on 2026-05-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_requestrecipient_otp_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrecipient',
            name='otp_is_used',
        ),
        migrations.RemoveField(
            model_name='requestrecipient',
            name='otp_used_at',
        ),
    ]
