# Generated by Django 4.2.16 on 2026-05-13 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_remove_file_files_owner_i_4bc251_idx_and_more'),
        ('sharing', '0003_filerequest_allowed_extensions_requestrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('zip_name', models.CharField(default='shared_files.zip', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.CharField(blank=True, max_length=512)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('files', models.ManyToManyField(related_name='zip_shares', to='files.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zip_shares',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['shared_by', 'status'], name='zip_shares_shared__ed93c5_idx'), models.Index(fields=['share_token'], name='zip_shares_share_t_85d081_idx')],
            },
        ),
    ]
