# Generated by Django 4.2.16 on 2026-05-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'is_favorite'], name='files_owner_i_56991e_idx'),
        ),
    ]
