# Generated by Django 4.2.16 on 2026-05-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_is_favorite_file_files_owner_i_56991e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest of file content (for duplicate detection).', max_length=64),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'original_name'], name='files_owner_i_4bc251_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'sha256'], name='files_owner_i_e34a5a_idx'),
        ),
    ]
