# Generated by Django 4.2.16 on 2026-05-12 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_sha256_file_files_owner_i_4bc251_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_owner_i_4bc251_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_owner_i_e34a5a_idx',
        ),
        migrations.AddField(
            model_name='file',
            name='scan_result',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='file',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('safe', 'Safe'), ('infected', 'Infected'), ('scan_failed', 'Scan Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='files_sha256_150e02_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['scan_status'], name='files_scan_st_a0358a_idx'),
        ),
    ]
